# Generated by Django 5.1.3 on 2026-10-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voi_start_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
