name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up SSH Key
      shell: bash
      run: |
        echo "${{ secrets.EC2_KEY }}" > ~/voi-start-key.pem
        chmod 400 ~/voi-start-key.pem

    - name: Deploy Code
      shell: bash
      run: |
        # Copy all project files to the EC2 instance
        scp -o StrictHostKeyChecking=no -i ~/voi-start-key.pem -r ./voi_start/* ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/voi_start/
        
        # SSH into the EC2 instance and deploy
        ssh -o StrictHostKeyChecking=no -i ~/voi-start-key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "
          cd /home/${{ secrets.EC2_USER }}/voi_start
          git pull
          docker compose pull
          docker compose --env-file .env up -d --build --force-recreate
        "
